name: CI
on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
    tags: ['*']
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - main
concurrency:
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install system prerequisites
        if: runner.os == 'Linux'
        run: sudo apt-get install -y patchelf
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
